version: "3.8"
services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "8100:5678"
    environment:
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - minha_rede

  gpt2:
    build: ./gpt2
    container_name: gpt2
    ports:
      - "8101:8000"
    restart: unless-stopped
    volumes:
      - gpt2_data:/app/data
    networks:
      - minha_rede
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4G

  gpt2-api:
    build: ./gpt2-api
    container_name: gpt2-api
    ports:
      - "8102:5000"
    depends_on:
      - gpt2
    restart: unless-stopped
    volumes:
      - gpt2-api_data:/app/data
    networks:
      - minha_rede
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: seu_usuario
      POSTGRES_PASSWORD: sua_senha
      POSTGRES_DB: gestor_financeiro
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - minha_rede

volumes:
  n8n_data:
  pgdata:
  gpt2_data:
  gpt2-api_data:

networks:
  minha_rede:
    driver: bridge